Fix the following bugs with upgrade from typescript 1.6: required new lodash.d.ts file: error TS1036: Statements are not allowed in ambient contexts. error TS2304: Cannot find name 'declare'.  error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.